network:
  ethernets:
    ens33:
      dhcp4: no
      addresses: [192.168.10.27/24]
      gateway4: 192.168.10.2
      nameservers:
          addresses: [1.1.1.1, 8.8.8.8]
      routes:
        - to: 10.200.0.0/24
          via: 192.168.10.29
  version: 2